//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Censo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Censo
    {
        public int IdCenso { get; set; }
        public byte[] FotoT { get; set; }
        public string NombreT { get; set; }
        public string EdadT { get; set; }
        public string SexoT { get; set; }
        public string TelefonoT { get; set; }
        public string CelularT { get; set; }
        public string EmailT { get; set; }
        public string DomicilioT { get; set; }
        public string EstadoCivilT { get; set; }
        public string HijosT { get; set; }
        public string EdadHijos { get; set; }
        public string ActividadT { get; set; }
        public string HorarioT { get; set; }
        public string EnfermedadT { get; set; }
        public byte[] FotoD { get; set; }
        public string NombreD { get; set; }
        public string PrimerApellidoD { get; set; }
        public string SegundoApellidoD { get; set; }
        public Nullable<System.DateTime> FechaNacD { get; set; }
        public string SexoD { get; set; }
        public string InstitucionD { get; set; }
        public string DiscapacidadD { get; set; }
        public string DiscapacidadOtraD { get; set; }
        public string PadecimientoD { get; set; }
        public string PadecimientoOtroD { get; set; }
        public string RevisionD { get; set; }
        public string TerapiaD { get; set; }
        public string TerapiaRecibeD { get; set; }
        public string TerapiaEducativaD { get; set; }
        public string EscuelaD { get; set; }
        public string ApoyoSocialD { get; set; }
        public string CualApoyo { get; set; }
        public string Actividades { get; set; }
        public string OtraActividad { get; set; }
        public string PlaticaHigiene { get; set; }
        public string PlaticaSexual { get; set; }
        public string Trabajar { get; set; }
    }
}
